---
title: "PM566 Assinment01"
author: "Wenjia Lu"
format:
  html:
    embed-resources: true
---

```{r}
### Q1 Read in data using data.table() and Conduct EDA checklist items 2-4 ###

## Download and read in data
setwd("~/Desktop/PM566/DATA") 
pm2.5_2002 <- data.table::fread("ad_viz_plotval_data2002.csv")
pm2.5_2022 <- data.table::fread("ad_viz_plotval_data2022.csv")

## Check the dimensions, headers, footers, var names and types
dim(pm2.5_2002)
head(pm2.5_2002)
tail(pm2.5_2002)
str(pm2.5_2002)

dim(pm2.5_2022)
head(pm2.5_2022)
tail(pm2.5_2022)
str(pm2.5_2022)

## Check for any data issues, particularly in key var
table(pm2.5_2002$`Daily Mean PM2.5 Concentration`)
table(pm2.5_2002$STATE)
table(pm2.5_2002$COUNTY)
table(pm2.5_2002$`Site Name`)
summary(pm2.5_2002$`Daily Mean PM2.5 Concentration`)

table(pm2.5_2022$`Daily Mean PM2.5 Concentration`)
table(pm2.5_2022$STATE)
table(pm2.5_2022$COUNTY)
table(pm2.5_2022$`Site Name`)
summary(pm2.5_2022$`Daily Mean PM2.5 Concentration`)

## Summary 
# There were some values of Daily Mean PM2.5 Concentration less than 0 ug/m3 LC in 2002, which is unreasonable, we need to remove these values.
pm2.5_2022 <- pm2.5_2022[`Daily Mean PM2.5 Concentration` >= 0] 
summary(pm2.5_2022$`Daily Mean PM2.5 Concentration`)
# For 2002 data frame, there were 15976 obs and 20 variables. For 2022 data frame, there were 55933 obs and 20 variables. The average Daily Mean PM2.5 Concentration in 2002 was 16.12 ug/m3 LC and in 2022 was 8.554 ug/m3 LC. 
# Daily mean of PM2.5 concentration in 2002 has higher median and mean value than in 2022, which possibly means that the Daily PM2.5 concentration decreased from 2002 to 2022. However 2022's Daily mean of PM2.5 concentration has a larger range than 2002's, which needs more analysis.  

```


```{r}
### Q2 Combine the two years of data into one data frame and Use the Date var to create a new col for year ###
library(tidyverse)
library(data.table)

## Combine two dataset
two_years_pm2.5 <- rbind(pm2.5_2002, pm2.5_2022)

## Use Date to create a new col 'year'
two_years_pm2.5 <- mutate(two_years_pm2.5, year = (rep(c(2002,2022), c(nrow(pm2.5_2002), nrow(pm2.5_2022)))))
two_years_pm2.5 <- as.data.table(two_years_pm2.5)

## Change the names of key var
setnames(two_years_pm2.5, "Daily Mean PM2.5 Concentration", "Daily PM2.5")
setnames(two_years_pm2.5, "Site Name", "SITE")
setnames(two_years_pm2.5, "SITE_LATITUDE", "lat")
setnames(two_years_pm2.5, "SITE_LONGITUDE", "lng")
head(two_years_pm2.5)

```


```{r}
### Q3 Create a basic map in leaflet() shows the loc of the sites ###
library(leaflet)
dat_stations <- (unique(two_years_pm2.5[,c("lat","lng","year")]))  
dim(dat_stations)

year.pal <- colorNumeric(c('green','red'), domain = dat_stations$year)

leaflet(two_years_pm2.5) %>%
  addProviderTiles('OpenStreetMap') %>% 
  addCircles(lat =~ lat, lng =~ lng, 
             color =~ year.pal(year), opacity = 1, fillOpacity = 1, radius = 100)

## Summary
# the figure below shows that the red spot has much higher density than the green spot. Also spreading in a much wider range than the green spot. 

```


```{r}
### Q4 Check for missing/implausible values of PM2.5, explore the proportions of each ###
library(arsenal)

## Check for missing or implausible values
## 1. At State level
summary(two_years_pm2.5$`Daily PM2.5`)
mean(is.na(two_years_pm2.5$`Daily PM2.5`))
pm2.5_order= two_years_pm2.5[order(`Daily PM2.5`)]
head(pm2.5_order)
tail(pm2.5_order)
# No missing or implausible values


## 2. At County level
pm2.5_2002 = two_years_pm2.5 %>% filter(year==2002) %>% distinct(COUNTY) 
pm2.5_2022 = two_years_pm2.5 %>% filter(year==2022) %>% distinct(COUNTY)
summary(comparedf(pm2.5_2002, pm2.5_2022, by="COUNTY"))

PM2.5_Country = two_years_pm2.5 %>% filter(two_years_pm2.5$COUNTY %in% intersect(pm2.5_2002$COUNTY, pm2.5_2022$COUNTY))
# There were 48 and 50 counties observed in 2002 and 2022 respectively. The unmatched counties were: Modoc(2002), Glenn, Madera, Tehama(all three from 2022).


## 3. At Site level. LA code is 37
PM2.5_LA = subset(two_years_pm2.5, COUNTY_CODE==37)
sum(PM2.5_LA$SITE=="")
all_la= subset(PM2.5_LA, PM2.5_LA$SITE != "")
PM2.5_LA_2002 = PM2.5_LA %>% filter(year==2002) %>% distinct(SITE) 
PM2.5_LA_2022 = PM2.5_LA %>% filter(year==2022) %>% distinct(SITE)
summary(comparedf(PM2.5_LA_2002, PM2.5_LA_2022, by="SITE"))

PM2.5_LA = two_years_pm2.5 %>% filter(two_years_pm2.5$SITE %in% intersect(PM2.5_LA_2002$SITE, PM2.5_LA_2022$SITE))
# For sites in LA, there were 7 site in common, but 10 sites were not shared by the two years, 3 sites only in 2002 and 8 sites only in 2022.

```


```{r}
### Q5 Explore the main Q of interest at three different spatial levels, create exploratory plots ###

## 1. At State level
Daily_PM2.5_Concentration <- (two_years_pm2.5$`Daily PM2.5`)
# Boxplot
two_years_pm2.5[!is.na(year)] %>%
ggplot() +
  geom_boxplot(mapping = aes(x = year, y = Daily_PM2.5_Concentration, group = year))
# Histogram
class(two_years_pm2.5$year) = "character"
ggplot(two_years_pm2.5, aes(x = Daily_PM2.5_Concentration)) +
  geom_histogram(aes(color = year, fill = year), 
                position = "identity", bins = 30, alpha = 0.4) +
  scale_color_manual(values = c("#00AFBB", "#E7B800")) +
  scale_fill_manual(values = c("#00AFBB", "#E7B800"))
# Line plots
ggplot(two_years_pm2.5) +
  geom_point(mapping = aes(x = lat, y = Daily_PM2.5_Concentration, color = year))
# Summary statistics
tapply(two_years_pm2.5$`Daily PM2.5`, two_years_pm2.5$year, summary)
# Conclusion
# At California State, we can see that the daily concentrations of PM2.5 decreased in average level over the last 20 years. Meanwhile, there were more extreme values of daily mean PM2.5 concentration in 2022 than in 2002. 


## 2. At County level
County = group_by(PM2.5_Country, year, COUNTY) %>% 
  summarize(`Daily PM2.5` = mean(`Daily PM2.5`, na.rm = TRUE), .groups = "drop") 

Daily_PM2.5_Concentration <- (County$`Daily PM2.5`)
# Boxplot
ggplot(County) +
  geom_boxplot(mapping = aes(x = year, y = Daily_PM2.5_Concentration, group = year))
# Summary statistics
tapply(County$`Daily PM2.5`, County$year, summary)
# Conclusion
# In County level, the daily concentrations of PM2.5 decreased in average level over the last 20 years.


## 3. At Site level
Site = group_by(PM2.5_LA, year, SITE) %>% 
  summarize(`Daily PM2.5` = mean(`Daily PM2.5`, na.rm = TRUE), .groups = "drop") 

Daily_PM2.5_Concentration <- (Site$`Daily PM2.5`)
# Boxplot
ggplot(Site) +
  geom_boxplot(mapping = aes(x = year, y = Daily_PM2.5_Concentration, group = year))
# Summary statistics
tapply(Site$`Daily PM2.5`, Site$year, summary)
# Conclusion
# In Site-LA level, the daily concentrations of PM2.5 decreased almost double in average level over the last 20 years.

```

